### ISSUE TITLE
needs fixing for 1.0 release

### ISSUE THREAD

**Issue by Skjolbir** [Paloys/FasterHardDrives#1]
needs fixing for 1.0 release on ficsit.app

**Comment by Paloys** [comment]
If you opened your eyes and looked at the description of the mod on ficsit.app, you would've realized this mod won't be updated anymore.
Use [Shorter Hard Drive Research](https://ficsit.app/mod/ShortenHardDriveResearch) by Robb instead, as he is an active modder I'm confident his mod will be updated soon 😊

**Comment by Skjolbir** [comment]
my apologies
